#!/usr/bin/env ruby

require 'bundler'

ENV['BUNDLE_GEMFILE'] ||= File.expand_path('./Gemfile')
Bundler.require(:default, :development)

Dotenv.load

require_relative '../lib/bot'

bot = Rebbot::Bot.new(
  discord_token: ENV['DISCORD_TOKEN'],
  cmd_prefix: ENV['PREFIX'] || '!',
  iex_tokens: {
    public: ENV['IEX_PUB_TOKEN'],
    secret: ENV['IEX_SECRET_TOKEN']
  }
)

pry
